name: Build and Deploy to Google Compute Engine

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    environment: main
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Create environment variable file
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env

      - name: Cache Gradle packages
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: 'Authenticate to GCP Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIP }}

      - name: 'Set up GCP SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use GCP CLI'
        run: 'gcloud info'